### ISSUE TITLE
Should step 4 and 5 from readme local development setup be removed?

### ISSUE THREAD

**Issue by nettum** [craftcms/spoke-and-chain#114]
### Description
Consider removing step 4 and 5 from readme -> Local Development -> Environment as `craft db/restore seed.sql` and `craft demos/seed` are defined in the `post-create-project-cmd` script inside `composer.json`.
The [Europa Museum Craft CMS Demo](https://github.com/craftcms/europa-museum/) seems to skip these steps, while this demo still has them.

**Comment by nfourtythree** [comment]
Readme has been updated to reflect current advised local development practices.

Thanks!
