### ISSUE TITLE
Cypress tests do not pass

### ISSUE THREAD

**Issue by piotrpog** [craftcms/spoke-and-chain#122]
For example - `checkout.spec.js` file. 

It checks for `cy.get('form#guest-checkout input[type=text]')`, but no such element exists, template uses `button` instead `input`. 

Or there are errors because of sticky header, cypress complains that it covers buttons:

```
Timed out retrying after 4050ms: cy.click() failed because this element:

<button class="button w-full sm:w-auto" type="submit" name="submit">Add to ...</button>

is being covered by another element:

<div class="relative lg:container lg:flex lg:items-center lg:justify-between">...</div>
```

This could be fixed by using `{ scrollBehavior: 'center' }`.

**Comment by nfourtythree** [comment]
This is now fixed on `stable`.

Thanks!
