### ISSUE TITLE
vlucas/phpdotenv version set to v3.6.10

### ISSUE THREAD

**Issue by piotrpog** [craftcms/spoke-and-chain#127]
I notices that vlucas/phpdotenv composer package is locked to older version - v3.6.10, while new Craft installs use 5.4.0. Is there any reason for that? 

I tried using codeception with this demo website, but because of that older dotenv version, conception tests do not work because they require methods that are only on newer versions.

```
Uncaught Error: Call to undefined method Dotenv\Dotenv::parse()
```

**Comment by piotrpog** [comment]
Just an update, i played with that a bit and when i change `phpdotenv` package to latest version, i need to add `bootstrap.php` from latest release of craft and replace `craft` and `web/index.php` to these from latest version to make everything work correctly. 

Maybe spoke & chain should be updated like this.

**Comment by nfourtythree** [comment]
This has now been completed.

Thanks!
