### ISSUE TITLE
Cypress tests not compatible with cypress 10.4.0

### ISSUE THREAD

**Issue by piotrpog** [craftcms/spoke-and-chain#128]
Today when i tried to run tests, it forced me to update to cypress 10.4.0 (the old version just would not run and only displayed update option in console - i dod not updated node, npm or modified `package.json` in any way).

With the new version of cypress, the naming scheme of tests changed (files now need to be named like `testName.cy.js` and be in `e2e` directory), `cypress.json` config file is no longer supported.

Also it seems that now browser console errors make tests fail, while earlier it did not seemed to be a case (i have console error of failing to load css chunk).

**Comment by piotrpog** [comment]
Just small update, cypress is not actually forcing me to update, it was because i tried to use globally installed version of cypress, not local one from installed in node_modules.

But the issue is still valid - tests are not updated to latest version of cypress. Are there any plans to update them?

**Comment by piotrpog** [comment]
One more issue.. it seems that using this old version of cypress (opr anything else that is included in package.json file) causes issues with node 16, and higher, at least on windows. Downgrading node do version 12 makes it work.

**Comment by piotrpog** [comment]
What is more, when we install node packages, we get this warning:
`added 2514 packages from 1011 contributors and audited 2522 packages in 1040.64s
found 36 vulnerabilities (4 low, 13 moderate, 17 high, 2 critical)`

**Comment by nfourtythree** [comment]
This was completed in the following PR: https://github.com/craftcms/spoke-and-chain/pull/132
