### ISSUE TITLE
`transform` parameter not utilized in responsive image component

### ISSUE THREAD

**Issue by johndwells** [craftcms/spoke-and-chain#25]
### Description

In the `_includes/components/images/responsive.twig` component, it accepts a `transform` parameter which if passed, should be applied to the image and used as the `src` attribute when outputting the image tag. However due to the source order, `src` always points to the image's original URL.

https://github.com/craftcms/spoke-and-chain/blob/develop/templates/_includes/components/images/responsive.twig#L16-L21:

```
{# Variables #}
{% set tagOptions = image ? {
    src: image.url,
    alt: showAlt ? image.title : null,
} : null %}
{% if transform and image %}{% do image.setTransform(transform) %}{% endif %}
```

Solution is to call `do image.setTransform()` _before_ setting `tagOptions`:

```
{% if transform and image %}{% do image.setTransform(transform) %}{% endif %}
{% set tagOptions = image ? {
    src: image.url,
    alt: showAlt ? image.title : null,
} : null %}
```

**Comment by mattstein** [comment]
Good catch, thank you @johndwells! 🎩
