### ISSUE TITLE
Craft can't fetch the `info` table row - during setup

### ISSUE THREAD

**Issue by acalvino4** [craftcms/spoke-and-chain#90]
### Description

Following the setup instructions listed here precisely, I get the following errors:
```
$ nitro craft demos/seed
connecting to spokeandchain.nitro
Could not open input file: craft
Error: exit status 1
$ ./craft demos/seed
 Craft can’t fetch the `info` table row.                                                                  
    Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'spokeandchain.info' doesn't exist    

Beginning seed ... 

Seeding Freeform data ... 
Error: Solspace\Freeform\Freeform::getInstance(): Return value must be of type Solspace\Freeform\Freeform, null returned
```

### Steps to reproduce

Go through the setup instructions in the README, and observe the error

### Additional info

- Craft version: 3.7
- PHP version: 8.0
- Database driver & version: mysql 8.0
- Plugins & versions:
```
    "craftcms/aws-s3": "^1.2",
    "craftcms/cms": "^3.7",
    "craftcms/commerce": "^3.4",
    "craftcms/redactor": "^2.8",
    "craftcms/store-hours": "2.1.1.1",
    "fakerphp/faker": "^1.9",
    "nystudio107/craft-seomatic": "^3.3.44",
    "nystudio107/craft-twigpack": "^1.2.15",
    "oberon/starfield": "^1.0",
    "putyourlightson/craft-sprig": "^1.3.3",
    "solspace/craft-freeform": "^3.11.9",
    "verbb/default-dashboard": "^1.0",
    "vlucas/phpdotenv": "^3.4.0",
    "wbrowar/guide": "^2.0"
```

**Comment by acalvino4** [comment]
Also, although it looks like my site container is running fine
![image](https://user-images.githubusercontent.com/43254861/149428693-06da544d-ec23-45eb-aef2-4d8a0239f7ca.png)
when I visit spokeandchain.nitro in my browser, I get a 404 from nginx.

**Comment by nfourtythree** [comment]
Hi @acalvino4 

Thank you for raising this issue.

I believe we might be missing a step in the installation instructions in the README.

Before you try to seed the demo data, so between steps 3 and 4 (as it currently stands) could you run the following command:

```bash
nitro craft db/restore seed.sql
```

You will probably see a warning about the info table but the last output should say `Restoring database backup ... done`

After that, you should then be able to run

```bash
nitro craft demos/seed
```

Let me know how you get on and we can get the README updated.

Thanks!

**Comment by acalvino4** [comment]
That seems to have worked - thanks!

**Comment by nfourtythree** [comment]
Thanks for letting us know.

We have now updated the installation/setup instructions.
